# Generated by Django 4.1.5 on 2023-01-30 14:58

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('column_separator', models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon')], max_length=1, verbose_name='Column separator')),
                ('string_character', models.CharField(choices=[('"', 'Double-quote'), ("'", 'Quote')], max_length=1, verbose_name='String character')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('from_range', models.BooleanField(default=False, verbose_name='View range: From')),
                ('to_range', models.BooleanField(default=False, verbose_name='View range: To')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FileCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('file', models.FileField(upload_to=user_app.models.FileCSV.upload_file, verbose_name='File')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.schema', verbose_name='Schema')),
            ],
            options={
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('from_range', models.IntegerField(blank=True, verbose_name='Range: From')),
                ('to_range', models.IntegerField(blank=True, verbose_name='Range: To')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.schema', verbose_name='Schema')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.type', verbose_name='Type')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
