# Generated by Django 4.1.5 on 2023-01-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_schema_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='from_range',
            field=models.IntegerField(null=True, verbose_name='Range: From'),
        ),
        migrations.AlterField(
            model_name='column',
            name='to_range',
            field=models.IntegerField(null=True, verbose_name='Range: To'),
        ),
    ]
