# Generated by Django 4.1.5 on 2023-01-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_column_from_range_alter_column_to_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='from_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Range: From'),
        ),
        migrations.AlterField(
            model_name='column',
            name='to_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Range: To'),
        ),
    ]
